# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d717050a230ff37540978d310c60b1fb81fd2678e9419d1345ded12509079534043053796344b7958897023bd3155b20ca81b1b0454f13d16eb10c508cfb1e24

test:
  secret_key_base: eed296dc6782104f350d93e8c96b5f41203e125b18c43669dbfc772861218646322c6c4d6c3e21c68bfe90e9ed48492518e5d62fc20cd3c96ea6aaa79526ab77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
